// tools/build-intake.mjs — generates supabase/functions/order-intake/index.ts (Etapa 3 doors-online).
//
//   node tools/build-intake.mjs        → writes the function (engine embedded STATICALLY)
//
// Why generated: Edge Functions (Deno Deploy) block runtime code-generation (`new Function`),
// so the index.html inline script is embedded as a real function body at BUILD time. Strict-mode
// compatibility is proven by tools/strict-probe.mjs (golden byte-identical under "use strict").
// Regenerate + redeploy whenever index.html changes engine behaviour.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'index.html'), 'utf8');
const src = (html.match(/<script[^>]*>([\s\S]*?)<\/script>/i) || [])[1];
if (!src) { console.error('inline <script> not found'); process.exit(1); }
const ids = [...new Set([...html.matchAll(/id="([A-Za-z_$][\w$]*)"/g)].map(m => m[1]))];

const out = `// GENERATED by tools/build-intake.mjs — DO NOT EDIT BY HAND.
// order-intake: receives kabacal-order/v1 from the FastCNC site bridge, generates
// .fastcnc + DXF + NC with the embedded Kabacal engine, stores them in the
// 'fastcnc-orders' bucket, records the order in public.fastcnc_orders, and emails
// services@fastcnc.co.uk when RESEND_API_KEY is configured.
// Engine source: index.html captured at build time (${new Date().toISOString().slice(0, 10)}).
import { createClient } from 'npm:@supabase/supabase-js@2';

const APP_IDS = ${JSON.stringify(ids)};

function runApp(window, document, localStorage, sessionStorage, alert, confirm, prompt, navigator, location, fetch, setTimeout, clearTimeout) {
"use strict";
${src}
;return {
  get items() { return items; }, get camPaths() { return camPaths; }, get camJob() { return camJob; },
  get project() { return project; }, get panelRooms() { return panelRooms; },
  mkItem, applyProfile, render, clearSel, tplApply, tpSheets, tpSegsForSheet,
  ncPegasus, buildDxfByThickness, buildFastCnc, calcQuote
};
}

function bootEngine() {
  const mkEl = () => { const el = { style: {}, dataset: {}, children: [], value: '', innerHTML: '', textContent: '', checked: false, options: [],
    classList: { add() {}, remove() {}, toggle() {}, contains: () => false },
    setAttribute() {}, getAttribute: () => null, appendChild(c) { el.children.push(c); return c; }, removeChild() {}, remove() {}, insertBefore() {},
    addEventListener() {}, removeEventListener() {}, focus() {}, select() {}, click() {}, closest: () => null,
    querySelector: () => mkEl(), querySelectorAll: () => [], getBoundingClientRect: () => ({ left: 0, top: 0, right: 0, bottom: 0, width: 0, height: 0 }),
    scrollIntoView() {}, contains: () => false }; return el; };
  const doc = { createElement: () => mkEl(), getElementById: () => mkEl(), querySelector: () => null, querySelectorAll: () => [],
    addEventListener() {}, removeEventListener() {}, body: mkEl(), documentElement: mkEl(), activeElement: null, write() {}, close() {} };
  const mkStore = () => { const m = new Map(); return { getItem: k => m.has(k) ? m.get(k) : null, setItem: (k, v) => m.set(k, String(v)), removeItem: k => m.delete(k), clear: () => m.clear() }; };
  const win = { addEventListener() {}, removeEventListener() {}, open: () => null, matchMedia: () => ({ matches: false, addEventListener() {} }), location: { href: '', search: '', origin: 'http://x', reload() {} } };
  win.window = win;
  APP_IDS.forEach(id => { if (!(id in globalThis)) globalThis[id] = mkEl(); });
  return runApp(win, doc, mkStore(), mkStore(), () => {}, () => true, () => null, { userAgent: 'edge' }, win.location, () => Promise.reject(new Error('offline')), () => 0, () => {});
}

// ---- kabacal-order/v1 adapter (mirror of tools/order-engine.mjs — keep in sync) ----
const STYLE_PRESETS = { 'plain-shaker': 'Plain Shaker' };
const TPL_BY_TH = { 18: 'tpl_plainshaker18', 22: 'tpl_plainshaker22' };
const DEFAULT_FRAME = 50;

export function orderToFiles(order) {
  if (!order || order.schema !== 'kabacal-order/v1') throw new Error('expected a kabacal-order/v1 payload');
  const eng = bootEngine();
  const o = order.order, tag = 'FC-' + o.number;
  eng.items.length = 0; eng.clearSel(); eng.panelRooms.length = 0; eng.camPaths.length = 0;
  eng.project.client = ((o.customer.first_name || '') + ' ' + (o.customer.last_name || '')).trim();
  eng.project.number = tag;
  eng.project.date = (o.created_gmt || '').slice(0, 10);
  eng.project.email = o.customer.email || '';
  eng.project.phone = o.customer.phone || '';
  eng.project.notes = (o.customer_note || '') && ('Customer note: ' + o.customer_note);
  const thicknesses = new Set();
  order.items.forEach((it, n) => {
    if (it.kind !== 'door') throw new Error('item ' + n + ': v1 handles doors only (got ' + it.kind + ')');
    const preset = STYLE_PRESETS[it.style];
    if (!preset) throw new Error('item ' + n + ': unsupported style "' + it.style + '"');
    if (!TPL_BY_TH[it.t_mm]) throw new Error('item ' + n + ': unsupported thickness ' + it.t_mm + 'mm');
    thicknesses.add(it.t_mm);
    const holes = +it.hinge_holes || 0;
    const hinges = holes > 0 ? { on: true, count: holes, side: /right/i.test(it.hinge_side || '') ? 'right' : 'left' } : { on: false };
    const f = DEFAULT_FRAME;
    eng.items.push(eng.mkItem('flat', it.w_mm, it.h_mm, it.qty, 'MDF ' + it.t_mm + 'mm', '8x4',
      { t: f, r: f, b: f, l: f }, null, tag + ' ' + it.name, hinges, { offsetName: 'None' }));
    eng.applyProfile(eng.items.length - 1, preset);
    if (it.cnc_notes) eng.project.notes += (eng.project.notes ? '\\n' : '') + 'Item ' + (n + 1) + ' CNC notes: ' + it.cnc_notes;
  });
  eng.render();
  eng.camPaths.length = 0;
  Object.assign(eng.camJob, { zZero: 'bed', datum: 'll', rapidGap: 20, approach: 5, orient: 'portrait' });
  thicknesses.forEach(th => eng.tplApply(TPL_BY_TH[th], true));
  const sheets = eng.tpSheets();
  const nc = sheets.map((f2, i) => ({ name: tag + '_S' + (i + 1) + '.nc', content: eng.ncPegasus(eng.tpSegsForSheet(f2)) }));
  const dxf = eng.buildDxfByThickness();
  const fastcnc = eng.buildFastCnc();
  return { fastcnc, dxf, nc };
}

// ---- HTTP handler (deps injectable for tests) ----
export async function handleOrderIntake(req, deps) {
  const { sb, env } = deps;
  const secret = env.get('FCNC_BRIDGE_SECRET');
  if (req.method !== 'POST') return Response.json({ error: 'POST only' }, { status: 405 });
  if (!secret || req.headers.get('x-fcnc-secret') !== secret) return Response.json({ error: 'bad secret' }, { status: 401 });

  let order;
  try { order = await req.json(); } catch { return Response.json({ error: 'invalid JSON' }, { status: 400 }); }
  if (!order || order.schema !== 'kabacal-order/v1' || !order.order || !order.order.id) {
    return Response.json({ error: 'expected kabacal-order/v1' }, { status: 422 });
  }
  const orderId = order.order.id, tag = 'FC-' + order.order.number;

  const existing = await sb.from('fastcnc_orders').select('id,status').eq('order_id', orderId).maybeSingle();
  if (existing.error) return Response.json({ error: 'db: ' + existing.error.message }, { status: 500 });
  if (existing.data && existing.data.status === 'files_generated') {
    return Response.json({ ok: true, duplicate: true, order: tag }, { status: 200 });
  }
  if (!existing.data) {
    const ins = await sb.from('fastcnc_orders').insert({
      order_id: orderId, order_number: String(order.order.number), site_url: order.site_url || '', payload: order,
    });
    if (ins.error) return Response.json({ error: 'db insert: ' + ins.error.message }, { status: 500 });
  }

  let files;
  try {
    const out = orderToFiles(order);
    files = [
      { name: tag + '.fastcnc.json', content: JSON.stringify(out.fastcnc, null, 1), type: 'application/json' },
      ...Object.entries(out.dxf).map(([th, c]) => ({ name: tag + '_' + th + '.dxf', content: c, type: 'application/dxf' })),
      ...out.nc.map(f => ({ name: f.name, content: f.content, type: 'text/plain' })),
    ];
  } catch (e) {
    await sb.from('fastcnc_orders').update({ status: 'failed', error: String(e && e.message || e), updated_at: new Date().toISOString() }).eq('order_id', orderId);
    return Response.json({ error: 'engine: ' + (e && e.message || e) }, { status: 422 });
  }

  const stored = [];
  for (const f of files) {
    const path = 'orders/' + tag + '/' + f.name;
    const up = await sb.storage.from('fastcnc-orders').upload(path, new Blob([f.content], { type: f.type }), { upsert: true });
    if (up.error) return Response.json({ error: 'storage: ' + up.error.message }, { status: 500 });
    stored.push({ name: f.name, path, bytes: f.content.length });
  }

  let emailStatus = 'skipped (no RESEND_API_KEY)';
  const resendKey = env.get('RESEND_API_KEY');
  if (resendKey) {
    const o = order.order, c = o.customer;
    const lines = order.items.map(it => '- ' + it.qty + 'x ' + it.name + ' ' + it.h_mm + 'x' + it.w_mm + 'x' + it.t_mm + 'mm, ' + it.finish
      + ', hinges: ' + it.hinge_holes + ' (' + (it.hinge_side || '-') + '/' + (it.hole_positions || '-') + ')'
      + (it.cnc_notes ? ', notes: ' + it.cnc_notes : '') + ' — £' + it.line_total);
    const body = ['New paid order ' + tag + ' (' + (order.site_url || '') + ')', '',
      'Customer: ' + c.first_name + ' ' + c.last_name, 'Email: ' + c.email, 'Phone: ' + (c.phone || '-'),
      'Billing: ' + c.billing_address, 'Shipping: ' + c.shipping_address, '',
      'Items:', ...lines, '', 'Total: ' + o.currency + ' ' + o.total + ' (site snapshot — authoritative)',
      'Payment: ' + o.payment_method + (o.transaction_id ? ' (' + o.transaction_id + ')' : ''), '',
      'Files (also in Supabase Storage fastcnc-orders/orders/' + tag + '):',
      ...stored.map(s => '- ' + s.name + ' (' + s.bytes + ' bytes)'), '',
      'Generated by Kabacal order-intake. Review before cutting — air-cut protocol applies.'].join('\\n');
    const resp = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + resendKey },
      body: JSON.stringify({
        from: env.get('FCNC_MAIL_FROM') || 'FAST CNC Orders <onboarding@resend.dev>',
        to: [env.get('FCNC_MAIL_TO') || 'services@fastcnc.co.uk'],
        subject: 'Production files — order ' + tag + ' (' + order.items.reduce((a, i) => a + i.qty, 0) + ' door(s))',
        text: body,
        attachments: files.map(f => ({ filename: f.name, content: btoa(unescape(encodeURIComponent(f.content))) })),
      }),
    });
    emailStatus = resp.ok ? 'sent' : 'failed HTTP ' + resp.status + ': ' + (await resp.text()).slice(0, 200);
  }

  const upd = await sb.from('fastcnc_orders').update({
    status: 'files_generated', files: stored, error: null,
    email_sent_at: emailStatus === 'sent' ? new Date().toISOString() : null,
    updated_at: new Date().toISOString(),
  }).eq('order_id', orderId);
  if (upd.error) return Response.json({ error: 'db update: ' + upd.error.message }, { status: 500 });

  return Response.json({ ok: true, order: tag, files: stored, email: emailStatus }, { status: 200 });
}

if (typeof Deno !== 'undefined' && Deno.serve) {
  const sb = createClient(Deno.env.get('SUPABASE_URL'), Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'));
  Deno.serve(req => handleOrderIntake(req, { sb, env: Deno.env }));
}
`;

const dir = join(root, 'supabase', 'functions', 'order-intake');
mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, 'index.ts'), out);
console.log('wrote supabase/functions/order-intake/index.ts (' + out.length + ' bytes, engine ' + src.length + 'B, ' + ids.length + ' ids)');
